"""事件类型——解析后的类型化回调消息。"""

from ._base import Event, SubTaskMixin, TaskChainMixin
from .global_events import (
    AllTasksCompletedEvent,
    AsyncCallInfoEvent,
    ConnectionEvent,
    DestroyedEvent,
    InitFailedEvent,
    InternalErrorEvent,
)
from .subtask_events import (
    FacilityEvent,
    OperBoxEvent,
    ProcessTaskEvent,
    RecruitResultEvent,
    RecruitTagsDetectedEvent,
    RecruitTagsRefreshedEvent,
    RecruitTagsSelectedEvent,
    StageDropsEvent,
    StageInfoEvent,
    SubTaskCompletedEvent,
    SubTaskErrorEvent,
    SubTaskStartedEvent,
    SubTaskStoppedEvent,
    UnknownSubTaskEvent,
)
from .taskchain_events import (
    TaskChainCompletedEvent,
    TaskChainErrorEvent,
    TaskChainExtraInfoEvent,
    TaskChainStartEvent,
    TaskChainStoppedEvent,
)

__all__ = [
    "Event",
    "TaskChainMixin",
    "SubTaskMixin",
    "InternalErrorEvent",
    "InitFailedEvent",
    "ConnectionEvent",
    "AllTasksCompletedEvent",
    "AsyncCallInfoEvent",
    "DestroyedEvent",
    "TaskChainErrorEvent",
    "TaskChainStartEvent",
    "TaskChainCompletedEvent",
    "TaskChainExtraInfoEvent",
    "TaskChainStoppedEvent",
    "SubTaskErrorEvent",
    "SubTaskStartedEvent",
    "SubTaskCompletedEvent",
    "SubTaskStoppedEvent",
    "ProcessTaskEvent",
    "StageDropsEvent",
    "StageInfoEvent",
    "RecruitTagsDetectedEvent",
    "RecruitResultEvent",
    "RecruitTagsRefreshedEvent",
    "RecruitTagsSelectedEvent",
    "FacilityEvent",
    "OperBoxEvent",
    "UnknownSubTaskEvent",
]
